import type { Metadata } from "next";
import { proximaNova } from "./styles/fonts";
import "./globals.scss";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru" className={proximaNova.variable}>
            <body>{children}</body>
        </html>
    );
}